name: Deploy Angular App to VPS (local build)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy via SSH (clone and build on VPS)
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          set -e

          cd /srv

          # Clone initial ou update si déjà existant
          if [ -d "cv" ]; then
            cd cv
            git reset --hard
            git pull origin main
          else
            git clone https://github.com/jbristhuille/cv.git cv
            cd cv
          fi

          # Build de l'image Docker localement
          docker build -t cv-angular:latest .

          # Redémarrage du conteneur
          docker stop cv || true
          docker rm cv || true
          docker run -d --name cv --restart always -p 8080:80 cv-angular:latest
