name: Rebuild CV container on VPS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: SSH into VPS and rebuild container
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          docker stop cv || true
          docker rm cv || true
          cd /srv/docker-cv
          docker build --no-cache -t jbristhuille/cv .
          docker run -d --name cv --restart always -p 8080:80 jbristhuille/cv:latest
